- name: Freshen GitHub for metrics user in VPs
  hosts: vps, c01
  remote_user: "{{ superuser }}"
  become_user: metrics
  become: yes
  tasks:
  - name: Freshen GitHub for metrics user in VPs
    git:
      repo: "https://github.com/icann/root-metrics.git"
      dest: /home/metrics/repo
