- name: Set up the machine as root
  hosts: all_vps  
  remote_user: "{{ superuser }}"
  become_user: root
  become: yes
  tasks:
  - name: Initialize apt
    apt:
      update_cache: true
  - name: Do the apt upgrade
    apt:
      upgrade: full
      force: true
  - name: Install all the needed packages
    apt:
      pkg: [curl, git, pyflakes3, python3-pip, python3-requests, rsync, scamper, sudo, traceroute, unzip]
  - name: Put .bashrc for root
    copy:
      src: ../bashrc-for-metrics-and-root
      dest: /root/.bashrc
  - name: Make /sftp for transfer user
    file:
      path: /sftp
      state: directory
      mode: go-w
  - name: Replace sshd_config
    copy:
      src: ../etc_sshd_config_shorter
      dest: /etc/ssh/sshd_config
  - name: Restart sshd after changing the config
    systemd:
      state: restarted
      name: sshd.service
      daemon_reload: yes      
  - name: Make user 'transfer'
    user:
      name: transfer
      home: /sftp/transfer
      shell: /bin/bash
  - name: Make user 'metrics'
    user:
      name: metrics
      home: /home/metrics
      shell: /bin/bash
- name: Set up transfer user
  hosts: all_vps
  remote_user: "{{ superuser }}"
  become_user: transfer
  become: yes
  tasks:
  - name: Set up id_rsa for transfer
    authorized_key:
      user: transfer
      key: "{{ lookup('file', '../Local/transfer_id_rsa.pub') }}"
  - name: Create Output/ for transfer
    file:
      path: /sftp/transfer/Output
      mode: go+w
      state: directory
  - name: Create AlreadySeen/ for transfer
    file:
      path: /sftp/transfer/AlreadySeen
      mode: go+w
      state: directory
- name: Set up metrics user
  hosts: all_vps
  remote_user: "{{ superuser }}"
  become_user: metrics
  become: yes
  tasks:
  - name: Put .bashrc for metrics
    copy:
      src: ../bashrc-for-metrics-and-root
      dest: /home/metrics/.bashrc
  - name: Put short-host-name.txt
    template:
      src: ../short-host-name.txt
      dest: /home/metrics/short-host-name.txt
  - name: make Logs/
    file:
      path: /home/metrics/Logs
      mode: u+wrx,go+rx
      state: directory
  - name: get dnspython
    shell:
      cmd: "pip3 install --user dnspython"
      creates: /home/metrics/.local/lib/python3.7/site-packages/dns
  - name: Pull or freshen the Github repo
    git:
      repo: 'https://github.com/icann/root-metrics.git'
      dest: /home/metrics/repo
      version: dnspython
  - name: Give the crontab entry for new_vantage_point_metrics.py
    cron:   # [mba] [wca]
      name: Get measurements
      minute: "0-59/5"
      job: "/home/metrics/repo/new_vantage_point_metrics.py >>/home/metrics/Logs/cron-alert.txt 2>&1"
