- name: Freshen GitHub for metrics user in VPs
  hosts: all_vps
  remote_user: "{{ superuser }}"
  become_user: root
  become: yes
  tasks:
  - name: Stop all metrics jobs
    command:
      cmd: "/usr/bin/pkill -u metrics"
    ignore_errors: true
  - name: Remove metrics
    command:
      cmd: "/usr/sbin/deluser --remove-home metrics"
      removes: "/home/metrics"
    ignore_errors: true
      